{ pkgs, dmenu, i3status}:
let
  lowbattery-alert = pkgs.callPackage ./lowbattery-alert.nix {};
  wallpaper-roller = pkgs.callPackage ./wallpaper-roller.nix {};
in
''
# Multi references:
# - https://github.com/lontivero/my-nixos-configuration/blob/master/configuration.nix
# - https://www.sglavoie.com/posts/2020/08/15/a-guided-tour-of-an-i3-configuration/#general-settings


# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod1

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
# exec --no-startup-id dex --autostart --environment i3

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
# exec --no-startup-id ${pkgs.xss-lock}/bin/xss-lock --transfer-sleep-lock -- ${pkgs.i3lock}/bin/i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
# exec --no-startup-id ${pkgs.networkmanagerapplet}/bin/nm-applet

# Use pactl to adjust volume in PulseAudio.
# set $refresh_i3status killall -SIGUSR1 i3status
# bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
# bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
# bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
# bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec ${pkgs.konsole}/bin/konsole # i3-sensible-terminal

# kill focused window
bindsym $mod+q kill

# start dmenu (a program launcher)
# bindsym $mod+d exec dmenu_run # Basic dmenu
# bindsym $mod+d exec --no-startup-id dmenu_run
# bindsym $mod+d exec --no-startup-id /.config/rofi/bin/launcher_text
bindsym $mod+d exec rofi -no-config -no-lazy-grab -show drun -modi drun -show-icons

# switch to any window with Rofi
# ⇒ this simulates the familiar behavior of Alt+Tab on Windows and allows you
#   to find windows by typing, but uses a better operating system to do it ;).
bindsym $mod+Tab exec "rofi -theme lb -font $rofi-font -show-icons -width 95 -show window"

# A more modern dmenu replacement is rofi:
# bindcode $mod+40 exec "rofi -modi drun,run -show drun"
# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
# bindcode $mod+40 exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus up
bindsym $mod+k focus down
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right



# alternatively, you can use the cursor keys:
# Commented because used for moving to activated workspaces
# bindsym $mod+Shift+Left move left
# bindsym $mod+Shift+Down move down
# bindsym $mod+Shift+Up move up
# bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+n split h

# split in vertical orientation
bindsym $mod+b split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# capture screen selection with scrot 
# bindsym --release $mod+Print exec ${pkgs.scrot}/bin/scrot -s -f $HOME/Screenshots/tmp.png -e '${pkgs.xclip}/bin/xclip -selection clipboard -t image/png -i $f'
# bindsym --release $mod+Shift+Print exec ${pkgs.scrot}/bin/scrot -s -f $HOME/Screenshots/`date +%Y-%m-%d_%H:%M:%S`.png

# browser
bindsym --release $mod+Shift+w exec ${pkgs.firefox}/bin/firefox

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1   1: Web
set $ws2   2: Terminal
set $ws3   3
set $ws4   4: Code
set $ws5   5: Code
set $ws6   6: Code
set $ws7   7: Doc
set $ws8   8
set $ws9   9: Conf
set $ws0   10: Chat

# determine which workspace appears on which screen
# ⇒ with a single output screen, this is not necessary
# workspace 1  $output-secondary
# workspace 2  $output-secondary
# workspace 3  $output-secondary
# workspace 4  $output-secondary
# workspace 5  $output-secondary
# workspace 6  $output-secondary
# workspace 7  $output-primary
# workspace 8  $output-primary
# workspace 9  $output-primary
# workspace 10 $output-primary

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws0

# Navigating workspace
bindsym $mod+Shift+Right workspace next
bindsym $mod+Shift+Left workspace prev

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1; workspace $ws1;
bindsym $mod+Shift+2 move container to workspace number $ws2; workspace $ws2;
bindsym $mod+Shift+3 move container to workspace number $ws3; workspace $ws3;
bindsym $mod+Shift+4 move container to workspace number $ws4; workspace $ws4;
bindsym $mod+Shift+5 move container to workspace number $ws5; workspace $ws5;
bindsym $mod+Shift+6 move container to workspace number $ws6; workspace $ws6;
bindsym $mod+Shift+7 move container to workspace number $ws7; workspace $ws7;
bindsym $mod+Shift+8 move container to workspace number $ws8; workspace $ws8;
bindsym $mod+Shift+9 move container to workspace number $ws9; workspace $ws9;
bindsym $mod+Shift+0 move container to workspace number $ws0; workspace $ws0;

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
# bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# Show gaps between open windows; requires i3-gaps fork
# gaps inner 32

# Windows have a border of 4 pixels; replace pixel with normal to show titlebar
# new_window pixel 8

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)

# Base bar
# bar {
#         status_command i3status
# }
# Start i3bar to display a workspace bar (plus the system information i3status if available)
bar {
    id bar-1
    font xft:Lato 11
    # $font-small
    # $output-secondary
    # mode invisible
    tray_output none
    status_command ${pkgs.i3status-rust}/bin/i3status-rs ${./i3status-rust.toml}
    position top

    colors {
        background #000000
        statusline #ffffff
        separator  #666666
#                          border  backgr. text
        focused_workspace  #4c7899 #285577 #ffffff #ffffff
        active_workspace   #333333 #5f676a #ffffff #3c3b37
        inactive_workspace #333333 #222222 #888888 #aea79f
        urgent_workspace   #2f343a #900000 #ffffff #ffffff
    }
}


# Theme colors
# class                   border  backgr. text    indic.  child_border
  # client.focused          #ffffff #ff0054 #ffffff #2e9ef4
  # client.focused_inactive #333333 #8338ec #ffffff #484e50
  client.unfocused        #333333 #000000 #bbbbbb #292d2e
  client.urgent           #2f343a #900000 #ffffff #900000
  client.placeholder      #F9FAF9 #061229 #FFFFFF #061229
  client.background       #000000

# assign [class="chromium"]           $ws1
assign [class=".*(F|f)irefox.*"]    $ws1
# assign [class="konsole"]            $ws2
# assign [class="konsole"]            $ws2
# assign [class="vscode"]             $ws4
# assign [class="vscode"]             $ws5
# assign [class="vscode"]             $ws6
assign [class="sublime3"]           $ws7
# assign [class="JDownloader"]        $ws8
# assign [class="Lxappearance"]       $ws9
# assign [class="Slack"]              $ws0


# Set background
exec_always --no-startup-id ${pkgs.nitrogen}/bin/nitrogen --restore
bindsym $mod+Pause mode "$mode_system"



# run special warning script
# exec --no-startup-id ${lowbattery-alert}/bin/lowbattery-alert.sh

# Wallpaper Script
exec --no-startup-id ${wallpaper-roller}/bin/wallpaper-roller.sh

# autostart
#exec_always start-pulseaudio-x11
exec_always --no-startup-id i3-msg 'workspace $ws1; exec firefox'
exec_always --no-startup-id i3-msg 'workspace $ws2; exec konsole'
# exec --no-startup-id i3-msg 'workspace $ws4; exec code'
exec_always --no-startup-id i3-msg 'workspace $ws7; exec sublime3'
exec_always --no-startup-id i3-msg 'workspace $ws7; exec konsole'
# exec --no-startup-id urxvt -name dropdown -e tmux
# exec --no-startup-id urxvt -name math -e /.config/i3/dropdowncalc

set $Locker ${pkgs.i3lock}/bin/i3lock && sleep 1

set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+s) shutdown
mode "$mode_system" {
    bindsym l exec --no-startup-id $Locker, mode "default"
    bindsym e exec --no-startup-id i3-msg exit, mode "default"
    bindsym s exec --no-startup-id $Locker && systemctl suspend, mode "default"
    bindsym h exec --no-startup-id $Locker && systemctl hibernate, mode "default"
    bindsym r exec --no-startup-id systemctl reboot, mode "default"
    bindsym Shift+s exec --no-startup-id systemctl poweroff -i, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

# scratchpad terminal
# exec --no-startup-id ${pkgs.alacritty}/bin/alacritty -name dropdown 

bindsym $mod+Shift+Return [instance="dropdown"] scratchpad show, move position center

for_window [instance="dropdown"] floating enable, resize set 800 600, move scratchpad


''
